name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    -
      name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    -
      uses: actions/checkout@v4
      name: Build the Docker image
    - 
      name: Run Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
          dockerfile: Dockerfile
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER }}
        password: ${{ secrets.TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:./"
        push: true
        tags: ${{ secrets.DOCKER }}/crypto-git:${{ github.run_number }}    
